package com.github.satori87.gdx.webaudio.source;

import com.github.satori87.gdx.webaudio.types.NoiseType;

/**
 * Generates continuous noise of a specified type (white, pink, or brownian).
 *
 * <p>Like other source nodes, this is a one-shot node: once stopped, it cannot be restarted.
 * Create a new instance for each use. The noise type is fixed at creation time.</p>
 */
public interface NoiseNode extends AudioScheduledSourceNode {

    /**
     * Returns the type of noise generated by this node.
     *
     * @return the noise type
     */
    NoiseType getType();
}
